(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s); const state={episode:0,spoilerLimit:16,view:'episodes',browseQuery:'',browseFilter:'all'};
const TYPE_MAPS={character:CHARACTERS,place:PLACES,object:OBJECTS,race:RACES};
const FILTERS=[['all','All'],['character','Characters'],['place','Places'],['object','Objects'],['race','Races']];
const clear=e=>{while(e.firstChild)e.removeChild(e.firstChild)};
const btn=(t,c,fn)=>{const b=document.createElement('button');b.type='button';b.className=c;b.textContent=t;if(fn)b.onclick=fn;return b};
const episodeTag=i=>i<8?`S1E${i+1}`:`S2E${i-7}`; const episodeName=i=>i<8?EP_NAMES.s1[i]:EP_NAMES.s2[i-8];
function firstReveal(e){const v=(e.summary||[]).map(x=>x.revealAt).filter(Number.isFinite);return v.length?Math.min(...v):1}
function entityVisible(t,id){const e=TYPE_MAPS[t]?.[id];return !!e&&firstReveal(e)<=state.spoilerLimit}
function visibleIdentity(e){return e?.identities?.filter(x=>x.revealAt<=state.spoilerLimit).sort((a,b)=>a.revealAt-b.revealAt).at(-1)||null}
function entityLabel(t,id){const e=TYPE_MAPS[t]?.[id];if(!e)return id;if(t==='character'){const x=visibleIdentity(e);if(x)return x.displayName||x.name;if(e.nameRevealAt&&e.nameRevealAt>state.spoilerLimit)return e.identities?.[0]?.name||id}return e.name||id}
function entityRole(t,id){const e=TYPE_MAPS[t]?.[id];if(!e)return '';if(t==='character'){const x=visibleIdentity(e);if(x?.role)return x.role}return e.role||''}
function visibleEntityNames(t,id){const e=TYPE_MAPS[t]?.[id];if(!e)return[];const n=[];if(!e.nameRevealAt||e.nameRevealAt<=state.spoilerLimit)n.push(e.name);(e.aliases||[]).forEach(x=>n.push(x));if(t==='character')(e.identities||[]).filter(x=>x.revealAt<=state.spoilerLimit).forEach(x=>{n.push(x.name);(x.aliases||[]).forEach(a=>n.push(a))});return[...new Set(n.filter(Boolean))]}
function episodeSections(i){const sid=i<8?'s1':'s2',local=i<8?i:i-8,season=SEASONS[sid];return Object.entries(season.storylines).map(([key,story])=>({key,story,episode:story.episodes[local]})).filter(x=>x.episode)}
function loadState(){const p=new URLSearchParams(location.search),saved=+localStorage.getItem('rop-spoiler-limit'),q=+p.get('spoilers');state.spoilerLimit=q>=1&&q<=16?q:(saved>=1&&saved<=16?saved:16);state.view=p.get('view')==='browse'?'browse':'episodes';const ep=+p.get('episode');state.episode=ep>=1&&ep<=state.spoilerLimit?ep-1:Math.min(state.spoilerLimit-1,15)}
function updateUrl(push=false){const p=new URLSearchParams();p.set('episode',state.episode+1);p.set('spoilers',state.spoilerLimit);if(state.view==='browse')p.set('view','browse');history[push?'pushState':'replaceState'](null,'',`${location.pathname}?${p}`)}
function buildDictionary(){const d=[];for(const[t,map]of Object.entries(TYPE_MAPS))for(const[id]of Object.entries(map)){if(!entityVisible(t,id))continue;visibleEntityNames(t,id).forEach(name=>d.push({name,id,type:t}))}return d.sort((a,b)=>b.name.length-a.name.length)}
function boundaryOK(text,start,len){const before=start?text[start-1]:'',after=text[start+len]||'';const word=c=>/^[\p{L}\p{N}_]$/u.test(c);return !word(before)&&!word(after)}
function appendLinkified(parent,text){if(!text)return;const dict=buildDictionary();if(!dict.length){parent.append(text);return}const esc=dict.map(x=>x.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));const re=new RegExp(`(${esc.join('|')})`,'giu'),by=new Map(dict.map(x=>[x.name.toLowerCase(),x]));let last=0;for(const m of text.matchAll(re)){if(!boundaryOK(text,m.index,m[0].length))continue;parent.append(text.slice(last,m.index));const hit=by.get(m[0].toLowerCase());const s=document.createElement('span');s.className='inline-link';s.textContent=m[0];s.onclick=()=>openEntity(hit.type,hit.id);parent.appendChild(s);last=m.index+m[0].length}parent.append(text.slice(last))}
function loreButton(id){const l=LORE[id];if(!l||l.revealAt>state.spoilerLimit)return null;const b=btn('i','lore-button',()=>openLore(id));b.setAttribute('aria-label','Show lore note');return b}
function entityButton(t,id,c='link-button'){return btn(entityLabel(t,id),c,()=>openEntity(t,id))}
function renderEpisodes(){const host=$('#episode-grid');clear(host);for(let i=0;i<16;i++){if(i===8){const d=document.createElement('div');d.className='season-divider';d.textContent='SEASON 2';host.appendChild(d)}const locked=i>=state.spoilerLimit,b=btn(episodeTag(i),'episode-card compact'+(i===state.episode?' selected':''),()=>{state.episode=i;renderEpisodes();renderEpisodePage();updateUrl(true)});b.disabled=locked;b.title=locked?'Hidden by spoiler limit':episodeName(i);host.appendChild(b)}}
function makeFact(label,ids,type){const d=document.createElement('div');d.innerHTML=`<strong>${label}: </strong>`;ids.filter(id=>type!=='character'||entityVisible(type,id)).forEach((id,i)=>{if(i)d.append(' · ');d.appendChild(entityButton(type,id))});return d}
function renderSection(item,index){const ep=item.episode,details=document.createElement('details');details.className='episode-section';const sum=document.createElement('summary');const title=document.createElement('span');title.className='section-title';appendLinkified(title,ep.summary);const meta=document.createElement('span');meta.className='section-meta';meta.textContent=(ep.place||[]).map(id=>PLACES[id]?.name).filter(Boolean).join(' · ');sum.append(title,meta);details.appendChild(sum);const body=document.createElement('div');body.className='section-body';const ul=document.createElement('ul');ul.className='detail-list';ep.beats.forEach(beat=>{const li=document.createElement('li');appendLinkified(li,beat.text);const l=loreButton(beat.lore);if(l)li.appendChild(l);ul.appendChild(li)});body.appendChild(ul);const facts=document.createElement('div');facts.className='fact-grid';facts.appendChild(makeFact('Place',ep.place||[],'place'));facts.appendChild(makeFact('Characters',ep.people||[],'character'));const why=document.createElement('div');why.innerHTML='<strong>Why it matters: </strong>';appendLinkified(why,ep.why);facts.appendChild(why);body.appendChild(facts);details.appendChild(body);return details}
function renderEpisodePage(){const host=$('#episode-card');clear(host);const i=state.episode,sections=episodeSections(i);const head=document.createElement('header');head.className='episode-page-head';head.innerHTML=`<span class="badge">${episodeTag(i)}</span><h2>${episodeName(i)}</h2><p class="muted">${sections.length} parts of the episode · tap a section to expand it</p>`;host.appendChild(head);const list=document.createElement('div');list.className='episode-sections';sections.forEach((s,n)=>list.appendChild(renderSection(s,n)));host.appendChild(list)}
function renderBrowseFilters(){const h=$('#browse-filters');clear(h);FILTERS.forEach(([id,label])=>h.appendChild(btn(label,'pill'+(state.browseFilter===id?' active':''),()=>{state.browseFilter=id;renderBrowseFilters();renderBrowseResults()})))}
function addBrowseCard(h,{type,title,sub,onClick}){const b=btn('', 'browse-card',onClick),p=document.createElement('span'),strong=document.createElement('b'),small=document.createElement('small');p.className='type-pill';p.textContent=type;strong.textContent=title;small.textContent=sub||'';b.append(p,strong,small);h.appendChild(b)}
function renderBrowseResults(){const h=$('#browse-results');clear(h);const q=state.browseQuery.trim().toLowerCase(),f=state.browseFilter,match=(...x)=>!q||x.join(' ').toLowerCase().includes(q);let count=0;for(const[t,map,label]of[['character',CHARACTERS,'Character'],['place',PLACES,'Place'],['object',OBJECTS,'Object'],['race',RACES,'Race']]){if(f!=='all'&&f!==t)continue;for(const[id,e]of Object.entries(map)){if(!entityVisible(t,id))continue;const title=entityLabel(t,id),sub=t==='character'?entityRole(t,id):(e.region||label);if(match(title,sub,visibleEntityNames(t,id).join(' '))){addBrowseCard(h,{type:label,title,sub,onClick:()=>openEntity(t,id)});count++}}}if(!count){const d=document.createElement('div');d.className='empty';d.textContent='No matches within your current spoiler limit.';h.appendChild(d)}}
function renderBrowse(){renderBrowseFilters();renderBrowseResults()}
function setView(v,push=true){state.view=v;$('#episodes-view').hidden=v!=='episodes';$('#browse-view').hidden=v!=='browse';$('#episodes-tab').classList.toggle('active',v==='episodes');$('#browse-tab').classList.toggle('active',v==='browse');if(v==='browse')renderBrowse();if(push)updateUrl(true)}
function openSheet(content){const root=$('#modal-root');clear(root);const back=document.createElement('div'),sheet=document.createElement('section');back.className='modal-backdrop';sheet.className='sheet';sheet.innerHTML='<div class="grabber"></div>';sheet.appendChild(content);back.appendChild(sheet);back.onclick=()=>clear(root);sheet.onclick=e=>e.stopPropagation();root.appendChild(back)}
function sheetHeader(type,name,role){const f=document.createDocumentFragment(),h=document.createElement('div'),d=document.createElement('div');h.className='sheet-head';d.innerHTML=`<span class="type-pill">${type}</span><h2>${name}</h2>${role?`<p class="muted">${role}</p>`:''}`;h.append(d,btn('×','close-button',()=>clear($('#modal-root'))));f.appendChild(h);return f}
function appearances(type,id){const names=visibleEntityNames(type,id).map(x=>x.toLowerCase()),out=[];for(let i=0;i<state.spoilerLimit;i++){const hit=episodeSections(i).some(({episode:ep})=>{if(type==='character'&&(ep.people||[]).includes(id))return true;if(type==='place'&&(ep.place||[]).includes(id))return true;const hay=[ep.summary,ep.why,...ep.beats.map(b=>b.text)].join(' ').toLowerCase();return names.some(n=>hay.includes(n))});if(hit)out.push({index:i,label:`${episodeTag(i)} — ${episodeName(i)}`})}return out}
function openEntity(type,id){const e=TYPE_MAPS[type]?.[id];if(!e||!entityVisible(type,id))return;const c=document.createElement('div');c.appendChild(sheetHeader(type,entityLabel(type,id),entityRole(type,id)));if(type==='character'&&e.race&&entityVisible('race',e.race)){const p=document.createElement('p');p.className='muted';p.textContent=RACES[e.race].name;c.appendChild(p)}(e.summary||[]).filter(x=>x.revealAt<=state.spoilerLimit).forEach(x=>{const p=document.createElement('p');appendLinkified(p,x.text);c.appendChild(p)});if(e.lore){const l=loreButton(e.lore);if(l)c.appendChild(l)}const rels=(e.relations||[]).filter(r=>r.revealAt<=state.spoilerLimit&&entityVisible('character',r.id));if(rels.length){const h=document.createElement('p');h.className='eyebrow';h.textContent='Connections';c.appendChild(h);const g=document.createElement('div');g.className='relation-grid';rels.forEach(r=>g.appendChild(btn(`${entityLabel('character',r.id)} — ${r.label}`,'relation-button',()=>openEntity('character',r.id))));c.appendChild(g)}if(type!=='race'){const apps=appearances(type,id);if(apps.length){const h=document.createElement('p');h.className='eyebrow';h.textContent='Appearances so far';c.appendChild(h);const g=document.createElement('div');g.className='appearance-grid';apps.forEach(a=>g.appendChild(btn(a.label,'appearance-button',()=>{clear($('#modal-root'));state.episode=a.index;setView('episodes',false);renderEpisodes();renderEpisodePage();updateUrl(true)})));c.appendChild(g)}}openSheet(c)}
function openLore(id){const l=LORE[id];if(!l||l.revealAt>state.spoilerLimit)return;const c=document.createElement('div');c.appendChild(sheetHeader('Lore note',l.title,''));const p=document.createElement('p');p.textContent=l.text;c.appendChild(p);openSheet(c)}
function openSettings(){const c=document.createElement('div');c.appendChild(sheetHeader('Spoiler settings','Choose the furthest episode you have seen','Everything after it stays hidden.'));const tabs=document.createElement('div'),list=document.createElement('div');tabs.className='filter-rail';list.className='settings-list';let season=state.spoilerLimit<=8?'s1':'s2';function draw(){clear(tabs);clear(list);['s1','s2'].forEach(s=>tabs.appendChild(btn(`Season ${s==='s1'?1:2}`,'pill'+(s===season?' active':''),()=>{season=s;draw()})));EP_NAMES[season].forEach((name,i)=>{const global=season==='s1'?i+1:i+9;list.appendChild(btn(`Episode ${i+1} — ${name}`,'settings-episode'+(global===state.spoilerLimit?' selected':''),()=>{state.spoilerLimit=global;state.episode=Math.min(state.episode,global-1);localStorage.setItem('rop-spoiler-limit',global);clear($('#modal-root'));renderAll();updateUrl()}))})}draw();c.append(tabs,list);openSheet(c)}
function settingsSummary(){const l=state.spoilerLimit,s=l<=8?'s1':'s2',n=l<=8?l:l-8;return `Season ${s==='s1'?1:2} · Episode ${n} — ${EP_NAMES[s][n-1]}`}
async function share(){updateUrl();try{if(navigator.share)await navigator.share({title:'The Rings of Power Episode Companion',url:location.href});else await navigator.clipboard.writeText(location.href)}catch(e){if(e?.name!=='AbortError')prompt('Copy this link:',location.href)}}
function renderAll(){$('#settings-summary').textContent=settingsSummary();renderEpisodes();renderEpisodePage();setView(state.view,false)}
$('#episodes-tab').onclick=()=>setView('episodes');$('#browse-tab').onclick=()=>setView('browse');$('#settings-button').onclick=openSettings;$('#share-button').onclick=share;$('#browse-search').oninput=e=>{state.browseQuery=e.target.value;renderBrowseResults()};window.onpopstate=()=>{loadState();renderAll()};loadState();renderAll();updateUrl();
})();