const names=["A Shadow of the Past","Adrift","Adar","The Great Wave","Partings"];
const colors={galadriel:"var(--c1)",southlands:"var(--c2)",elrond:"var(--c3)",harfoots:"var(--c4)",isildur:"var(--c5)"};
const root=document.getElementById("rop-storylines"),picker=document.getElementById("episode-picker");
const spoilerSelect=document.getElementById("spoiler-limit"),storyView=document.getElementById("explore-view"),browseView=document.getElementById("browse-view"),browseResults=document.getElementById("browse-results"),browseSearch=document.getElementById("browse-search"),shareButton=document.getElementById("share-button"),exploreTab=document.getElementById("explore-tab"),browseTab=document.getElementById("browse-tab");
let currentStory="galadriel",currentEpisode=0,spoilerLimit=5,currentView="story";

function firstAvailable(s,max=spoilerLimit){return s.episodes.findIndex((e,i)=>Boolean(e)&&i<max)}
function params(){const p=new URLSearchParams(location.search);return {story:p.get("story"),episode:Number(p.get("episode")),spoilers:Number(p.get("spoilers")),view:p.get("view")}}
function updateUrl(replace=true){const p=new URLSearchParams();p.set("story",currentStory);p.set("episode",String(currentEpisode+1));p.set("spoilers",String(spoilerLimit));if(currentView!=="story")p.set("view",currentView);const url=`${location.pathname}?${p.toString()}`;(replace?history.replaceState:history.pushState).call(history,null,"",url)}
function loadState(){const q=params();const saved=Number(localStorage.getItem("rop-spoiler-limit"));if(Number.isInteger(q.spoilers)&&q.spoilers>=1&&q.spoilers<=5)spoilerLimit=q.spoilers;else if(saved>=1&&saved<=5)spoilerLimit=saved;if(q.story&&STORIES[q.story])currentStory=q.story;if(Number.isInteger(q.episode)&&q.episode>=1&&q.episode<=5)currentEpisode=q.episode-1;if(q.view==="browse")currentView="browse";if(!STORIES[currentStory].episodes[currentEpisode]||currentEpisode>=spoilerLimit)currentEpisode=firstAvailable(STORIES[currentStory]);}

function episodes(){const s=STORIES[currentStory];picker.innerHTML=s.episodes.map((e,i)=>{const locked=i>=spoilerLimit;const unavailable=!e;const disabled=locked||unavailable;let blurb="";if(locked)blurb="Hidden by spoiler limit";else if(unavailable)blurb="Not shown in this episode";else blurb=e.blurb;return `<button class="episode-btn" data-episode="${i}" aria-pressed="${i===currentEpisode}" ${disabled?"disabled":""}><span class="episode-number">Episode ${i+1}</span><span class="episode-name">${names[i]}</span><span class="episode-blurb">${blurb}</span></button>`}).join("");picker.querySelectorAll("button:not(:disabled)").forEach(b=>b.onclick=()=>{currentEpisode=+b.dataset.episode;episodes();detail();updateUrl(false)})}
function detail(){const s=STORIES[currentStory],e=s.episodes[currentEpisode];if(!e)return;document.getElementById("detail-picture").setAttribute("href",`#${s.art}`);document.getElementById("detail-episode").textContent=`Episode ${currentEpisode+1}`;document.getElementById("detail-title").textContent=names[currentEpisode];document.getElementById("detail-summary").textContent=e.summary;document.getElementById("detail-beats").innerHTML=e.beats.map(x=>`<li>${x}</li>`).join("");document.getElementById("detail-place").textContent=e.place;document.getElementById("detail-people").textContent=e.people;document.getElementById("detail-why").textContent=e.why}
function renderStory(){const s=STORIES[currentStory];root.style.setProperty("--story-color",colors[currentStory]);document.getElementById("story-title").textContent=s.title;document.getElementById("story-cast").textContent=s.cast;document.getElementById("story-location").textContent=s.location;document.querySelectorAll(".story-choice").forEach(b=>{b.setAttribute("aria-pressed",b.dataset.story===currentStory);b.style.setProperty("--story-color",colors[b.dataset.story])});if(!s.episodes[currentEpisode]||currentEpisode>=spoilerLimit)currentEpisode=firstAvailable(s);episodes();detail()}

function visibleEvents(){const rows=[];Object.entries(STORIES).forEach(([key,s])=>s.episodes.forEach((e,i)=>{if(e&&i<spoilerLimit)rows.push({storyKey:key,story:s,episode:i,event:e})}));return rows}
function renderBrowse(){const q=(browseSearch.value||"").trim().toLowerCase();const rows=visibleEvents().filter(r=>!q||[r.story.title,r.story.cast,r.story.location,r.event.summary,r.event.place,r.event.people,r.event.why,...r.event.beats].join(" ").toLowerCase().includes(q));if(!rows.length){browseResults.innerHTML='<div class="empty cardish">No matching storyline moments within your spoiler limit.</div>';return}const grouped={};rows.forEach(r=>{(grouped[r.storyKey]??=[]).push(r)});browseResults.innerHTML=Object.entries(grouped).map(([key,items])=>`<section class="browse-card" style="--story-color:${colors[key]}"><h3>${STORIES[key].title}</h3><div class="chip-row">${items.map(r=>`<button class="chip" data-story="${r.storyKey}" data-episode="${r.episode}"><strong>Episode ${r.episode+1}</strong><small>${r.event.blurb}</small></button>`).join("")}</div></section>`).join("");browseResults.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{currentStory=b.dataset.story;currentEpisode=+b.dataset.episode;setView("story");renderStory();updateUrl(false);window.scrollTo({top:0,behavior:"smooth"})})}
function setView(view){currentView=view;const browse=view==="browse";storyView.hidden=browse;browseView.hidden=!browse;exploreTab.setAttribute("aria-pressed",String(!browse));browseTab.setAttribute("aria-pressed",String(browse));if(browse)renderBrowse();updateUrl()}

spoilerSelect.value=String(spoilerLimit);spoilerSelect.onchange=()=>{spoilerLimit=+spoilerSelect.value;localStorage.setItem("rop-spoiler-limit",String(spoilerLimit));if(currentEpisode>=spoilerLimit||!STORIES[currentStory].episodes[currentEpisode])currentEpisode=firstAvailable(STORIES[currentStory]);renderStory();renderBrowse();updateUrl()};
document.querySelectorAll(".story-choice").forEach(b=>b.onclick=()=>{currentStory=b.dataset.story;currentEpisode=firstAvailable(STORIES[currentStory]);renderStory();updateUrl(false)});
exploreTab.onclick=()=>setView("story");
browseTab.onclick=()=>setView("browse");
browseSearch.addEventListener("input",renderBrowse);
shareButton.onclick=async()=>{updateUrl();const url=location.href;try{if(navigator.share)await navigator.share({title:"The Rings of Power Storyline Explorer",url});else{await navigator.clipboard.writeText(url);shareButton.textContent="Link copied";setTimeout(()=>shareButton.textContent="Share this view",1600)}}catch(e){if(e?.name!=="AbortError")prompt("Copy this link:",url)}};
window.addEventListener("popstate",()=>{loadState();spoilerSelect.value=String(spoilerLimit);renderStory();setView(currentView)});

loadState();spoilerSelect.value=String(spoilerLimit);renderStory();setView(currentView);updateUrl();